station_pig_monitor.Rmd:
  path: dev/station_pig_monitor.Rmd
  state: active
  R:
  - R/fid_monitor.R
  - R/monitor_schedule.R
  - R/other_monitor.R
  - R/station_monitor.R
  tests: []
  vignettes: vignettes/basic-usage.Rmd
  inflate:
    flat_file: dev/station_pig_monitor.Rmd
    vignette_name: Basic Usage
    open_vignette: true
    check: true
    document: true
    overwrite: ask
