# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Calculate Total Feed Intake Per Location
#'
#' This function aggregates total feed intake across a specified date range for each location.
#' The feed intake data is first summed per location and date, then transformed to kilograms
#' and formatted to wide format with locations as rows and dates as columns.
#'
#' @param data A data table that must include at least 'location', 'date', 'visit_time', 
#'             and 'feed_intake' columns. 'visit_time' should be convertible to date and time.
#' @param days An integer specifying the number of days to include in the analysis up to and including
#'             the reference date.
#' @param ref_date A Date object used as the reference date for filtering data; defaults to the current
#'                 system date.
#'
#' @return Returns a data table in wide format with locations as rows and formatted dates as columns.
#'         Each entry is the summed feed intake for that date and location, converted to kilograms.
#'         An additional 'all_feedintake' column is included, showing the total feed intake for each
#'         location across all dates.
#' 
#' @export
#' 
#' @note This function expects that the input data is pre-cleaned and correctly formatted. 
#'       Errors may occur if 'visit_time' cannot be properly converted.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(all_feedintake(data = data, days = 5))
all_feedintake <- function(data, days, ref_date = Sys.Date()) {
  visit_time <- . <- feed_intake <- location <- NULL
  data <- data.table::copy(unique(data))
  processed_data <- data[, `:=`(c("date", "time"), data.table::IDateTime(visit_time))
  ][date >= (ref_date - days) & date <= ref_date,
    .(sum_feedintake = sum(feed_intake) / 1000),
    by = .(location, date)][, date := format(date, "%m-%d")][, location := as.character(location)]


  # Convert to wide format
  res <- dcast(processed_data, location ~ date, value.var = "sum_feedintake")
  numeric_cols <- setdiff(names(res), "location")
  res[, all_feedintake := round(rowSums(.SD, na.rm = TRUE), 2), .SDcols = numeric_cols]
  res[, (numeric_cols) := lapply(.SD, function(x) round(x, digits = 2)), .SDcols = numeric_cols][]
  # Return processed data table
  return(res)
}
