# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Compute Outlier Statistics and Time-based Metrics
#'
#' This function analyzes weight data to identify outliers using the Interquartile Range (IQR) method,
#' and computes time-based metrics for data entries within a specified number of days from a reference date.
#' It also reshapes the results into a wide format, separating the percentage of weight outliers and other metrics
#' like count of observations and total duration by location and date.
#'
#' @param data data.table, required.
#'   The input data table which must contain the following columns: `visit_time` (POSIXct), `location` (character),
#'   `responder` (character), `weight` (numeric, in grams), and `duration` (numeric, in seconds).
#' @param days integer, required.
#'   The number of days before the reference date to include in the analysis.
#' @param ref_date Date, optional.
#'   The specific date to use as the reference for filtering data; defaults to the current system date.
#'
#' @return A list of two data.tables:
#' \itemize{
#'   \item `weight_outlier`: A data table in wide format showing the percentage of weight outliers
#'                           per location across the specified dates.
#'   \item `feedintake`: A data table in wide format showing the count of observations and total
#'                       duration in hours per location across the specified dates.
#' }
#' 
#' @export
#' 
#' @note
#' The function assumes that the input data has all the required columns. The 'visit_time' should
#' be in POSIXct format to correctly convert to dates. Make sure the data is pre-cleaned to avoid errors
#' due to missing values, especially in the 'location' and 'responder' columns.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(extreme_time_n(data = data, days = 5))
extreme_time_n <- function(data, days, ref_date = Sys.Date()) {
  visit_time <- location <- . <- responder <- weight <- duration <- outlier <- NULL
  data <- data.table::copy(data)
  # Ensure 'visit_time' is a proper date-time format
  data_temp <- data[, `:=`(c("date", "time"), data.table::IDateTime(visit_time))
  ][date >= (ref_date - days) & date <= ref_date
  ][, unique(.SD)
  ][, date := format(date, format = "%m-%d")
  ][!is.na(location), .(location, date, responder, weight, duration)][!is.na(responder)]

  # Calculate Interquartile Range (IQR) and identify outliers
  data_temp[, outlier := {
    Q1 <- quantile(weight, 0.25, na.rm = TRUE)
    Q3 <- quantile(weight, 0.75, na.rm = TRUE)
    IQR <- Q3 - Q1
    (weight < (Q1 - 1.5 * IQR)) | (weight > (Q3 + 1.5 * IQR))
  }, by = .(location, date, responder)]

  # Compute statistics for each location and date
  extreme_stats <- data_temp[, .(
    extreme_weight = 100 * sum(outlier) / .N,   # Percentage of outliers
    n = .N,                                 # Total count of observations
    time = sum(duration) / 3600             # Total duration in hours
  ), by = .(location, date)]

  # Reshape data to wide format
  extreme_stats_wide <- dcast(extreme_stats, location ~ date, value.var = "extreme_weight")
  n_time_wide <- dcast(extreme_stats, location ~ date, value.var = c("n", "time"))

  # Round numeric columns to two decimal places
  numeric_cols <- setdiff(names(extreme_stats_wide), c("location"))
  extreme_stats_wide[, (numeric_cols) := lapply(.SD, round, digits = 2), .SDcols = numeric_cols]
  numeric_cols <- grep("time", names(n_time_wide), value = TRUE)
  n_time_wide[, (numeric_cols) := lapply(.SD, round, digits = 2), .SDcols = numeric_cols]
  return(list(weight_outlier = extreme_stats_wide, feedintake = n_time_wide))
}
