# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Hourly Statistics Computation
#'
#' The `hour_stat` function computes hourly statistics for given data,
#' including the number of visits, total feed time, and total feed intake,
#' grouped by location and hour. This function is designed for processing
#' time-series data related to feeding or visit behaviors.
#'
#' @param data data.table, required.
#'   The input data table which must contain the following columns:
#'   `visit_time` (POSIXct), `location` (character), `duration` (numeric, in minutes),
#'   and `feed_intake` (numeric, in grams).
#' @param target_date Date, optional.
#'   The specific date for which the data should be filtered. Defaults to 35 days prior
#'   to today (using `Sys.Date() - 35`).
#'
#' @return A list of data.tables containing hourly statistics:
#' \itemize{
#'   \item `visit_n`: Number of visits per location per hour.
#'   \item `feed_time`: Total feed time in hours per location per hour.
#'   \item `feed_intake`: Total feed intake in kilograms per location per hour.
#' }
#' 
#' @export
#' 
#' @note
#' The function requires that the `data` table contains specific columns named
#' `visit_time`, `location`, `duration`, and `feed_intake`. The `visit_time` should
#' be in POSIXct format for accurate processing. 
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(hour_stat(data = data))
hour_stat <- function(data, target_date = Sys.Date() - 1) {
  visit_time <- location <- duration <- . <- n <- feedintake <- NULL
  # Validate if required columns exist
  required_cols <- c("visit_time", "location", "duration", "feed_intake")
  if (!all(required_cols %in% names(data))) {
    stop("Data is missing one or more of the required columns: visit_time, location, duration, feed_intake")
  }

  # Ensure the target_date is a Date object
  if (!inherits(target_date, "Date")) {
    target_date <- as.Date(target_date)
  }

  # Process and filter data for the target date
  processed_data <- data[, `:=`(date = as.Date(visit_time),
                                hour = data.table::hour(visit_time))
  ][date == target_date][!is.na(location)][, `:=`(n = .N, feed_time = sum(duration)/60, feedintake = sum(feed_intake)/1000), by = .(location, hour)
  ][, .(location, date, hour, n, feed_time, feedintake)][, unique(.SD)]

  # Round numeric columns to two decimal places
  numeric_cols <- grep("feed_time|feedintake", names(processed_data), value = TRUE)
  data_temp <- processed_data[, (numeric_cols) := lapply(.SD, function(x) round(x, digits = 2)), .SDcols = numeric_cols]

  # Cast data for visualization or further analysis
  visit_n <- data_temp[, dcast(.SD, location ~ hour, value.var = "n")]
  feed_time <- data_temp[, dcast(.SD, location ~ hour, value.var = "feed_time")]
  feed_intake <- data_temp[, dcast(.SD, location ~ hour, value.var = "feedintake")]

  return(list(visit_n = visit_n, feed_time = feed_time, feed_intake = feed_intake))
}
