# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Calculate Mean Weight for Specified Location and Date Range
#' 
#' This function processes a dataset to extract weights by specified house (part of location), 
#' calculates mean weights per house over a given number of days from a reference date, and 
#' returns the data in a wide format with dates as rows and houses as columns.
#' 
#' @param data A data frame that must include the columns: "location", "date", and "weight".
#' @param house_width A string indicating the number of characters to use from the 'location'
#'                    column to create the 'house' identifier. Defaults to "1".
#' @param days An integer specifying the number of days to include in the analysis
#'                  back from the reference date.
#' @param ref_date A Date object used as the reference date for filtering data. 
#'                 Defaults to the current system date.
#'
#' @return Returns a data frame in wide format where each column represents a house
#'         and each row represents a date within the specified range. Values are mean weights
#'         (in kilograms, rounded to two decimal places) for each house-date combination.
#' 
#' @export
#'
#' @note If 'data' does not contain the necessary columns, the function will stop with an error message.
#'       It is crucial to ensure that the 'location' and 'date' columns are formatted correctly.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' head(house_weight(data = data, days = 5))
house_weight <- function(data, house_width = "1", days, ref_date = Sys.Date()) {
  house <- location <- mean_weight <- weight <- . <- NULL
  data <- process_data(data)

  # Validate necessary columns presence
  necessary_cols <- c("location", "date", "weight")
  if (!all(necessary_cols %in% names(data))) {
    stop("Data must include the necessary columns: location, date, and weight.")
  }
  
  # Create 'house' column by extracting specified width from 'location'
  data[, house := paste0("house_", substr(location, 1, house_width))]

  # Filter data for the last specified number of days from a reference date
  filtered_data <- data[date >= (ref_date - days) & date < ref_date, ]

  # Calculate mean weight per location and date, adjust weight scale
  stat_data <- filtered_data[, mean_weight := mean(weight) / 1000, by = .(house, date)
  ][, .(date, house, mean_weight)
  ][, unique(.SD)][, date := format(date, "%m-%d")]

  # Remove duplicate entries and reshape data to wide format
  result_data <- dcast(stat_data, date ~ house, value.var = "mean_weight")

  # Round numeric columns to two decimal places
  numeric_cols <- setdiff(names(result_data), "date")
  result_data[, (numeric_cols) := lapply(.SD, round, digits = 2), .SDcols = numeric_cols][]

  return(result_data)
}
