# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Calculate Feed Intake by House and Date
#'
#' This function calculates the total feed intake for each 'house' (a subset of 'location') over a specified
#' date range, and presents the data in a wide format. The function preprocesses the data to ensure proper 
#' formatting and then groups by 'house' and 'date' to summarize feed intake, which is then converted to kilograms.
#'
#' @param data A data table that must include at least 'location', 'date', and 'feed_intake' columns.
#'             It is expected that the data is already in a suitable format for processing.
#' @param house_width An integer specifying the number of characters from the start of the 'location'
#'                    field to define a 'house'.
#' @param days An integer specifying the number of days to include in the analysis up to and including
#'             the reference date.
#' @param ref_date A Date object used as the reference date for filtering data; defaults to the current
#'                 system date.
#'
#' @return Returns a data table in wide format where each row represents a date and each column a house.
#'         The entries are the summed feed intake for each house on each date, in kilograms. An additional
#'         column 'all_feedintake' shows the total feed intake across all houses for each date.
#' 
#' @export
#' 
#' @note This function depends on another function 'process_data' to preprocess the data. Errors may occur if
#'       the input data or the 'process_data' function are not correctly configured to handle the data.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(house_feedintake(data = data, house_width = "1", days = 5))
house_feedintake <- function(data, house_width, days, ref_date = Sys.Date()) {
  house <- location <- . <- feed_intake <- NULL

  data <- process_data(data)

  # Step 1: Create 'house' from the first characters of 'location' and filter by date
  data[, house := substr(location, 1, house_width)]
  filtered_data <- data[date >= (ref_date - days) & date <= ref_date][, date := format(date, "%m-%d")]

  # Step 2: Calculate sum of 'feed_intake' per 'house' and 'date', dividing by 1000
  summarized_data <- filtered_data[, .(sum_feed_intake = sum(feed_intake) / 1000), by = .(house, date)]

  # Step 3: Remove duplicates if any exist
  unique_data <- unique(summarized_data, by = c("house", "date"))

  # Step 4: Reshape data to wide format
  wide_data <- dcast(unique_data, date ~ house, value.var = "sum_feed_intake")

  # Step 5: Calculate total feed intake across all houses for each date
  numeric_cols <- setdiff(names(wide_data), "date")
  wide_data[, all_feedintake := rowSums(.SD, na.rm = TRUE), .SDcols = numeric_cols]

  # Round numeric columns to two decimal places
  numeric_cols <- setdiff(names(wide_data), "date")
  wide_data[, (numeric_cols) := lapply(.SD, round, digits = 2), .SDcols = numeric_cols][]

  return(wide_data)
}

#' Merge Data and Calculate Mean Feed Intake
#'
#' This function merges two datasets based on the 'date' column and calculates the mean feed intake
#' for each common house present in both datasets. It also handles the renaming of overlapping columns
#' and rounds numerical values for better presentation.
#'
#' @param feedintake A data frame containing feed intake data with a 'date' column.
#' @param n A data frame containing count data with a 'date' column.
#'
#' @return Returns a merged data frame with all rows included from both input frames. Suffixes "_feed" 
#'         and "_n" are added to overlapping column names from the 'feedintake' and 'n' datasets respectively. 
#'         The function also adds new columns representing the mean feed intake per common house.
#' 
#' @note It is crucial to ensure that both data frames include a 'date' column for the merge operation.
#'       The function assumes that all numeric values need to be rounded to two decimal places.
#' @noRd
merge_data <- function(feedintake, n) {
  . <- NULL
  # Merge hh2 and hh by "date", including all rows and adding suffixes to overlapping column names
  res3 <- merge(feedintake, n, by = "date", all = TRUE, suffixes = c("_feed", "_n"))

  # Extract column names exclusive to hh2 (excluding "date" and "sum_feed_intake")
  cols_feed <- names(feedintake)[!names(n) %in% c("date", "all_feedintake")]

  # Extract column names exclusive to hh (excluding "date")
  cols_n <- names(n)[!names(n) %in% c("date")]

  # Identify common columns between hh2 and hh for calculating mean feed intake
  intersect_house <- intersect(cols_feed, cols_n)

  # Append suffixes to column names for the merged table
  cols_feed_name <- paste0(intersect_house, "_feed")
  cols_n_name <- paste0(intersect_house, "_n")

  # Calculate mean feed intake for each common house and assign it to new columns
  res3[, paste0(intersect_house, "_mean_feed") := Map(function(feed, n) res3[[feed]] / res3[[n]],
                                                      cols_feed_name, cols_n_name)]

  # Identify and round double columns to three decimal places
  double_cols <- names(res3)[sapply(res3, is.double)]
  res3[, (double_cols) := lapply(.SD, function(x) round(x, digits = 2)), .SDcols = double_cols]

  return(res3)
}
