# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Analyze Low Feed Intake
#'
#' This function processes a dataset to calculate the total feed intake per location, date,
#' and responder. It then identifies days where the sum of feed intake is below a threshold,
#' specifically less than 0.5 kg. The results are returned in a wide format with each location
#' and responder combination as a row and dates as columns.
#'
#' @param data A data table that must include the columns: 'location', 'date', 'responder', 
#'             and 'feed_intake'. The 'visit_time' must be able to be converted to IDateTime format.
#' @param days An integer specifying the number of days to include in the analysis up to and including
#'             the reference date.
#' @param ref_date A Date object used as the reference date for filtering data; defaults to the current
#'                 system date.
#'
#' @return Returns a data table in wide format where each row represents a combination of location and
#'         responder, columns are dates, and values are the summed feed intake that are below the threshold
#'         of 0.5 kg. Also includes a 'sum_feedintake' column which is the total sum of feed intake across
#'         the period for each row.
#' 
#' @export
#' 
#' @note This function assumes that the input data has been preprocessed to include the necessary columns.
#'       It will stop and raise an error if the 'visit_time' cannot be converted to date and time format.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(low_feedintake(data = data, days = 5))
low_feedintake <- function(data, days, ref_date = Sys.Date()) {
  visit_time <- . <- feed_intake <- location <- responder <- sum_feedintake <- NULL
  data <- data.table::copy(unique(data))
  processed_data <- data[, `:=`(c("date", "time"), data.table::IDateTime(visit_time))
  ][date >= (ref_date - days) & date <= ref_date
  ][, .(sum_feedintake = sum(feed_intake) / 1000), by = .(location, date, responder)][
    , date := format(date, "%m-%d")]

  # Filter entries where 'sum_feedintake' is less than 0.5
  processed_data <- processed_data[sum_feedintake < 0.5]

  # Convert to wide format
  data_wide <- dcast(processed_data, location + responder ~ date, value.var = "sum_feedintake")
  # Calculate sum across numeric columns for each row and round the results
  numeric_cols <- setdiff(names(data_wide), c("location", "responder"))
  res <- data_wide[, sum_feedintake := round(rowSums(.SD, na.rm = TRUE), digits = 2), .SDcols = numeric_cols][]
  # Sort by 'sum_feed_intake'
  setorder(res, responder, -sum_feedintake, na.last = TRUE)  # Sort in descending order

  return(res)
}
