# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Merge Data and Calculate Mean Feed Intake
#'
#' This function merges two datasets based on the 'date' column and calculates the mean feed intake
#' for each common house present in both datasets. It also handles the renaming of overlapping columns
#' and rounds numerical values for better presentation.
#'
#' @param feedintake A data frame containing feed intake data with a 'date' column.
#' @param n A data frame containing count data with a 'date' column.
#'
#' @return Returns a merged data frame with all rows included from both input frames. Suffixes "_feed" 
#'         and "_n" are added to overlapping column names from the 'feedintake' and 'n' datasets respectively. 
#'         The function also adds new columns representing the mean feed intake per common house.
#' 
#' @note It is crucial to ensure that both data frames include a 'date' column for the merge operation.
#'       The function assumes that all numeric values need to be rounded to two decimal places.
#' @noRd
merge_data <- function(feedintake, n) {
  . <- NULL
  # Merge hh2 and hh by "date", including all rows and adding suffixes to overlapping column names
  res3 <- merge(feedintake, n, by = "date", all = TRUE, suffixes = c("_feed", "_n"))

  # Extract column names exclusive to hh2 (excluding "date" and "sum_feed_intake")
  cols_feed <- names(feedintake)[!names(n) %in% c("date", "all_feedintake")]

  # Extract column names exclusive to hh (excluding "date")
  cols_n <- names(n)[!names(n) %in% c("date")]

  # Identify common columns between hh2 and hh for calculating mean feed intake
  intersect_house <- intersect(cols_feed, cols_n)

  # Append suffixes to column names for the merged table
  cols_feed_name <- paste0(intersect_house, "_feed")
  cols_n_name <- paste0(intersect_house, "_n")

  # Calculate mean feed intake for each common house and assign it to new columns
  res3[, paste0(intersect_house, "_mean_feed") := Map(function(feed, n) res3[[feed]] / res3[[n]],
                                                      cols_feed_name, cols_n_name)]

  # Identify and round double columns to three decimal places
  double_cols <- names(res3)[sapply(res3, is.double)]
  res3[, (double_cols) := lapply(.SD, function(x) round(x, digits = 2)), .SDcols = double_cols]

  return(res3)
}
