# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Monitor all by hands
#' 
#' Combine the `fid_monitor`, `station_monitor`, and `table_monitor` functions together.
#' 
#'
#' @param data data.frame, required. The input data frame containing the data to be processed.
#' @param begin_date An optional Date object or character string specifying the beginning date for the data to be processed. If not provided, all dates in the data will be considered.
#' @param house_width character, optional. A character string representing the house width. Default is "1".
#' @param days integer, optional. An integer representing the number of days for the analysis.
#' @param save_path character, required. A character string representing the path where the output file will be saved. 
#'
#' @return
#' 
#' @export
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' monitor_all(data, begin_date = "2024-05-01", days = 5, save_path = "C:/Users/Dell/Downloads/test")
monitor_all <- function(data, begin_date, house_width = "1", days, save_path) {
  pptsdm::fid_monitor(data, begin_date, station_type = "nedap", save_path)
  pptsdm::station_monitor(data, begin_date, station_type = "nedap", save_path)
  pptsdm::table_monitor(data, house_width, days, ref_date = Sys.Date(), save_path)
}
