# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Count Responders by Location and Date
#'
#' This function processes a dataset to calculate the number of responders per specified 'house'
#' (a subset of the 'location' field) for each date within a specified number of days from a reference date.
#' The data is first processed to ensure the 'date' column is in Date format, 'house' is extracted from
#' 'location', and duplicates are removed. The output is provided in wide format with dates as rows
#' and houses as columns.
#'
#' @param data A data table that must include the columns: 'location', 'date', 'responder'.
#'             The function expects that 'date' can be converted into Date format.
#' @param house_width An integer specifying the number of characters from the start of the 'location'
#'                    field to define a 'house'.
#' @param days An integer specifying the number of days to include in the analysis back from the
#'             reference date.
#' @param ref_date A Date object used as the reference date for filtering data; defaults to the current
#'                 system date.
#'
#' @return Returns a data table in wide format where each row represents a date and each column a house.
#'         Each entry is the count of responders for that house and date.
#' 
#' @export
#' 
#' @note This function depends on another function 'process data' to first ensure the data is in the correct
#'       format. It is crucial that the input data and the 'process_data' function are properly configured
#'       to handle the data correctly.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(number_location(data = data, house_width = "1", days = 5))
number_location <- function(data, house_width, days, ref_date = Sys.Date()) {
  house <- location <- . <- responder <- NULL
  # Ensure date column is in Date format
  data <- process_data(data)

  # Step 1: Create 'house' column by extracting specified characters from 'location'
  # Step 2: Filter data within the last 'days' from 'ref_date'
  # Step 3: Remove duplicate rows based on 'house', 'date', 'responder'
  # Consolidate these steps to streamline operations
  data <- data[, house := substr(location, 1, house_width)
  ][date >= (ref_date - days) & date <= ref_date
  ][, date := format(date, "%m-%d")][, .(house, date, responder)
  ][, .N, by = .(house, date, responder)]

  # Step 4: Group by 'house' and 'date' to count the number of responders
  summary_data <- data[, .(count = .N), by = .(house, date)]

  # Step 5: Reshape the data into wide format using 'dcast'
  # 'date' as rows, 'house' as columns, and 'count' as values
  result_data <- dcast(summary_data, date ~ house, value.var = "count")

  return(result_data)
}
