# WARNING - Generated by {fusen} from dev/station_pig_monitor.Rmd: do not edit by hand

#' Analyze Missing Responder Data
#'
#' This function processes a dataset to identify and summarize the occurrences of NA values in the
#' 'responder' column within a specified number of days from a reference date. It converts dates,
#' removes duplicates, and aggregates NA counts per location and date. The output is presented in
#' a wide format with locations as rows and formatted dates as columns.
#'
#' @param data A data table that must include the columns: 'location', 'date', 'visit_time', and 'responder'.
#' @param days An integer specifying the number of days to include in the analysis back from the reference date.
#' @param ref_date A Date object used as the reference date for filtering data; defaults to the current system date.
#'
#' @return Returns a data table in wide format where each row represents a location and each column a date.
#'         Entries are the counts of NAs found in the 'responder' column for that location and date. 
#'         An additional 'total_nas' column shows the sum of NAs across all dates for each location.
#'
#' @export
#' 
#' @note This function stops execution and produces an error if the input data does not contain all the required columns.
#'       Ensure that 'location', 'date', 'visit_time', and 'responder' columns are formatted correctly and present.
#' @examples
#' # Load CSV data
#' data <- data.table::fread("C:/Users/Dell/Documents/projects/pptsdm_data/ppt_monitor_test_data.csv")
#' print(responder_na(data = data, days = 5))
responder_na <- function(data, days, ref_date = Sys.Date()) {
  visit_time <- n <- responder <- . <- location <- sum_n <- total_nas <- NULL
  data <- copy(data)
  # Convert visit_time to date and time columns and filter data by the given date range
  processed_data <- data[, `:=`(c("date", "time"), data.table::IDateTime(visit_time))
  ][date >= (ref_date - days) & date < ref_date
  ][, unique(.SD)  # Remove duplicate entries
  ][, n := fifelse(is.na(responder), 1L, 0L), by = .(location, date)  # Count NAs in responder column
  ][, sum_n := sum(n), by = .(location, date)  # Sum the NA counts by location and date
  ][, date := format(date, format="%y-%m-%d")  # Format date for consistency in output
  ][, .(location, date, sum_n)  # Select necessary columns
  ][, unique(.SD)  # Remove any duplicates after processing
  ]

  # Reshape the processed data to wide format using location as rows and dates as columns
  wide_data <- dcast(processed_data, location ~ date, value.var = "sum_n")
  wide_data[, location := as.character(location)]  # Convert 'location' to character for consistent data types

  # Calculate the total number of NAs for each location across all date columns
  numeric_cols <- setdiff(names(wide_data), "location")
  wide_data[, total_nas := rowSums(.SD, na.rm = TRUE), .SDcols = numeric_cols][]

  return(wide_data)
}
